### Problem statement
***
The following assignment concerns the numpy.random package in Python [2]. You are
required to create a Jupyter [5] notebook explaining the use of the package, including
detailed explanations of at least five of the distributions provided for in the package.
There are four distinct tasks to be carried out in your Jupyter notebook.
***
1. Explain the overall purpose of the package.
2. Explain the use of the “Simple random data” and “Permutations” functions.
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers.


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


np.random.randint(2,7,(8,3))

array([[2, 6, 4],
       [2, 2, 5],
       [6, 3, 5],
       [3, 4, 4],
       [5, 6, 4],
       [6, 5, 5],
       [2, 5, 3],
       [6, 3, 3]])

### NumPy overall purpose overview
***
NumPy- Numerical Python is a fundamental Python package for scientific computing and Data Science. It provides tools to work with multidimensional arrays and matrices, improving computational speed up to 50x compared to traditional Python lists. Mostly written in C/C# and optimised to work with latest CPU architectures that constitutes to a very strong and efficient performance while working with logical and mathematical operations on complex arrays[https://www.w3schools.com/python/numpy/numpy_intro.asp] Numpy was created by Travis Oliphant[https://en.wikipedia.org/wiki/Travis_Oliphant] by adding numerous modifications to previously popular Numeric package subsequently NumPy became very popular open-source software with robust community support and development.


## Numpy.random 
***
### Explain the overall purpose of the numpy.random package.

Numpy.random package is used to generate random numbers and multi-dimensional arrays; this output would be considered to be pseudorandom- it might seem output is different every time generation took place yet as computers are programmed to generate these number and arrays on pre-set sequence therefore it can be reproduced making it pseudorandom. Method is clearly visible when using seeds to get random reproduceable data.

## Simple random data
***
### numpy.random.rand

This function allows for generation of random uniform distribution sample of 0 to but not including 1. Array dimensions can be selected by editing parameters as required **numpy.random.rand(rows,columns)**

In [33]:
# Importing Numpy
import numpy as np
# Generating random array of 4 rows and 2 columns
np.random.rand(4,2)

array([[0.84091902, 0.79388084],
       [0.25842259, 0.88321931],
       [0.80541472, 0.7825515 ],
       [0.48074729, 0.20414964]])

### numpy.random.randn

This function returns a sample of values for standard distribution.

In [36]:
np.random.randn(10)

array([-0.63504434, -0.31256284,  0.80350803,  1.04913834,  0.58138318,
       -1.21002914,  0.1260498 ,  0.96283582,  0.26743149,  1.34159418])

### numpy.random.randint

This function generates random integers on chosen low, high and size values

### numpy.random.Generator.integers

### numpy.random.Generator.random

### numpy.random.Generator.choice

### numpy.random.Generator.bytes

## Permutations
***

### numpy.random.Generator.shuffle

### numpy.random.Generator.permutation

### numpy.random.Generator.permuted

## Distributions
***

Explain the use and purpose of at least five “Distributions” functions.

Explain the use of seeds in generating pseudorandom numbers.

### numpy.random.default_rng()

### References

#### 062 NumPy Random Seed Youtube video
https://www.youtube.com/watch?v=y4t8MuKqKt8

  

https://realpython.com/python-random/#how-random-is-random

https://realpython.com/numpy-tutorial/#data-science-operations-filter-order-aggregate

https://www.w3schools.com/python/numpy/numpy_random.asp