### Problem statement
***
The following assignment concerns the numpy.random package in Python. You are
required to create a Jupyter. notebook explaining the use of the package, including
detailed explanations of at least five of the distributions provided for in the package.
There are four distinct tasks to be carried out in your Jupyter notebook.
***
[1](#NumPy-overall-purpose-overview). Explain the overall purpose of the package.\
[2](#Simple-random-data). Explain the use of the “Simple random data” and “Permutations” functions.\
[3](#Distributions). Explain the use and purpose of at least five “Distributions” functions.\
[4](#Seeding-explain). Explain the use of seeds in generating pseudorandom numbers.


In [1]:
# Importing required packages
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### NumPy overall purpose overview
***
NumPy- Numerical Python is a fundamental Python package for scientific computing and Data Science. It provides tools to work with multidimensional arrays and matrices, improving computational speed up to 50x compared to traditional Python lists. Mostly written in C/C# and optimised to work with latest CPU architectures that constitutes to a very strong and efficient performance while working with logical and mathematical operations on complex arrays[(w3schools)](https://www.w3schools.com/python/numpy/numpy_intro.asp). Numpy was created by [Travis Oliphant](https://en.wikipedia.org/wiki/Travis_Oliphant) by adding numerous modifications to previously popular Numeric package subsequently NumPy became very popular open-source software with robust community support and development.


## Numpy.random Package
***
### Explain the overall purpose of the numpy.random package.

Numpy.random package is used to generate random numbers and multi-dimensional arrays; this output would be considered to be pseudorandom- it might seem output is different every time generation took place yet as computers are programmed to generate these number and arrays on pre-set sequence therefore it can be reproduced making it pseudorandom. Method is clearly visible when using seeds to get random reproduceable data.

### Generator

Numpy versions released following v1.17.0 can be set up with different types of generators that provides improved statistical properties comapred against legacy Mersenne Twister pseudo-random number generator. In the new version 64bit Permuted Congruential Generator is used as a default. Method uses two steps for random number generation: BitGenerator produces random values, Generator uses these values to create requested distributions equivalents. [Numpy-Random Sampling](https://numpy.org/doc/stable/reference/random/index.html)

In [2]:
# Importing random generator and assigning it to rng variable
from numpy.random import default_rng

rng = default_rng()

## Simple random data
***


### numpy.random.Generator.integers

This method allows for generation of random uniform distribution sample from zero to but not including one. Array dimensions can be selected by editing parameters as required \
**numpy.random.Generator.integers( low value inclusive , high value exclusive , size = (rows , columns), endpoint = if True- changes high value to inclusive)** \
[Numpy-Integers](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html)

In [11]:
# Generating random integers from 1 to 12 inclusive in array 5 rows and 3 columns
rng.integers(1,12,(5,3),endpoint=True)

array([[ 2,  4,  4],
       [ 4,  4,  9],
       [ 3,  7,  4],
       [11,  5,  5],
       [10,  7, 11]], dtype=int64)

### numpy.random.Generator.random

This method returns random float values in a range from zero inlusive to one exclusive [Numpy-Random](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html) \
**random.Generator.random(size=None, dtype=np.float64, out=None)**

In [4]:
# Generating 20 random floats
rng.random(20)

array([0.84929841, 0.66799413, 0.97331924, 0.09563933, 0.01577221,
       0.97281347, 0.33042724, 0.31271258, 0.35905268, 0.37820206,
       0.29751192, 0.27114623, 0.48080254, 0.73709431, 0.14546231,
       0.08185604, 0.65629686, 0.94813357, 0.36502385, 0.94990372])

### numpy.random.Generator.choice

This method return a sample of values from specified array, probabililty of each value can be set by user or uniform random sample will be returned. [Numpy-Choice](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html) \
**random.Generator.choice(array to choose from , size= number of choices(default to one if not selected), replace= if True each value can be selected multiple times, p= probablities set for each value, axis=0, shuffle=True)**

In [10]:
# Array of 5 integers within 0 to but not including 3.
rng.choice(3,5)

array([2, 0, 0, 2, 2], dtype=int64)

In [34]:
# Array of 5 integers 
a = np.arange(9)
print("Number array from 0 to 8: {}" .format(a))
# Assining probabilities and returning sample of 5
rng.choice(a, 5, p=[0.2, 0.3, 0.05, 0, 0.2, 0, 0.1, 0.1, 0.05])

Number array from 0 to 8: [0 1 2 3 4 5 6 7 8]


array([1, 7, 0, 8, 1])

### numpy.random.Generator.bytes

This method returns specified nuber of random bytes [Numpy-Bytes](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.bytes.html) Random bytes generator is commonly used for [salting](https://en.wikipedia.org/wiki/Salt_(cryptography)) the passwords before they are hashed- adding random data before it is encrypted for storing in data base.
**numpy.random.Generator.bytes(bytes lenght required)**

In [6]:
rng.bytes(2)

b'\x1ax'

## Permutations
***

[Permutation](https://www.merriam-webster.com/dictionary/permutation) definition acording as per Merriam-Webster:
1. Often major or fundamental change (as in character or condition) based primarily on rearrangement of existent elements
2. A form or variety resulting from such change
3. The act or process of changing the lineal order of an ordered set of objects
4. An ordered arrangement of a set of objects

### numpy.random.Generator.shuffle

This method rearranges existing array without changing its values.

In [52]:
# Generating array with values 0 to 10
b = np.arange(11)
print(b)
# Shuffling generated array
rng.shuffle(b)
# Outputing array that has been shuffled
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  4  9  6  8  3  1 10  7  5  2]


### numpy.random.Generator.permutation

This method permutes the array provided but does not override original array, a shuffled copy of an array is created and saved in the memory.

In [56]:
# Generating array with values 0 to 10
c = np.arange(11)
print(c)
# Shuffling generated array and saving it as d
d= rng.permutation(c)
print(d)
# Outputing original array to confirm there was no change
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  4  1  9  3  2  5  8  7 10  6]
[ 0  1  2  3  4  5  6  7  8  9 10]


### numpy.random.Generator.permuted

## Distributions
***

Explain the use and purpose of at least five “Distributions” functions.

## numpy.random.Generator.normal

## numpy.random.Generator.uniform

## numpy.random.Generator.f

In [61]:
rng.f(1,2,50)

array([3.49416840e-01, 2.62130479e-01, 2.45873756e-01, 8.55511600e-01,
       4.72985118e+00, 8.83630952e+00, 2.98682688e+00, 4.92976143e-01,
       3.78905566e-01, 1.16188987e+00, 1.32547772e+01, 1.31882323e+01,
       8.30056251e+01, 6.22245039e-01, 3.58363331e+00, 6.20515229e-01,
       9.55310260e-01, 2.08271576e+00, 1.23432509e-02, 4.94210063e+00,
       5.94284865e-02, 9.59412926e+00, 8.71619377e-01, 1.88344213e-02,
       3.39587839e-01, 2.90707054e-02, 1.83218703e-01, 8.25693571e-02,
       4.13319008e+00, 1.27968956e+00, 2.68001765e-01, 1.95800354e+00,
       5.70879234e+00, 4.82094353e-02, 3.07522513e-02, 8.33502267e-02,
       7.71771107e-01, 4.97324575e-03, 4.65113931e-01, 1.21622090e+00,
       3.89841545e-01, 1.73631991e+00, 1.89910297e+00, 1.12836841e+01,
       1.89683526e-01, 1.68515502e+00, 3.15153454e+00, 4.17867219e+00,
       2.68852828e+00, 1.20658651e+00])

## numpy.random.Generator.dirichlet


Explain the use of seeds in generating pseudorandom numbers.

### Seeding explain
***

### References
***

#### 062 NumPy Random Seed Youtube video
https://www.youtube.com/watch?v=y4t8MuKqKt8

  

https://realpython.com/python-random/#how-random-is-random

https://realpython.com/numpy-tutorial/#data-science-operations-filter-order-aggregate

https://www.w3schools.com/python/numpy/numpy_random.asp

https://realpython.com/how-to-use-numpy-arange/

https://numpy.org/doc/stable/reference/generated/numpy.arange.html